filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/sample.log

output.logstash:
  enabled: true
  hosts: ["logstash:5044"]

# setup.template.name: "filebeat-"
# setup.template.pattern: "filebeat-*"
# setup.dashboards.enabled: true

# setup.kibana:
#   host: "http://kibana:5601"
#   username: elastic
#   password: password
# output.elasticsearch:
#   hosts: ["http://localhost:9200"]
#   username: elastic
#   password: password
#   index: "filebeat-%{[beat.version]}-%{+yyyy.MM.dd}"
